apiVersion: v1
kind: BuildConfig
metadata:
  name: gsi-enablement-one.springbootmicroservice-balaaus
  labels:
    app: SpringBootMicroservice-BalaAus
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/gsi-enablement-one/SpringBootMicroservice-BalaAus.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-bala-austin
        - name: BRANCH
          value: master
